---

postgresql_users:
  - name: postgres
    pass: Zaq1Xsw2
    encrypted: yes
    state: "present"

postgresql_databases:
  - name: ansible-test-database
    owner: postgres
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"

postgresql_user_privileges:
  - name: postgres
    db: ansible-test-database
    priv: "ALL"
    role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE,INHERIT,REPLICATION"

postgresql_shared_preload_libraries:
  - pg_stat_statements

postgresql_wal_level: hot_standby
postgresql_hot_standby: on
postgresql_wal_log_hints: on
postgresql_max_wal_senders: 2
postgresql_wal_keep_segments: 64
postgresql_max_replication_slots: 16

postgresql_max_connections: 500
postgresql_shared_buffers: 512MB
postgresql_effective_cache_size: 1536MB
postgresql_maintenance_work_mem: 128MB
postgresql_work_mem: 524kB
postgresql_checkpoint_completion_target: 0.9
postgresql_wal_buffers: 16MB
postgresql_default_statistics_target: 100
postgresql_random_page_cost: 4
postgresql_effective_io_concurrency: 2
postgresql_max_wal_size: 4GB
postgresql_min_wal_size: 1GB
