---

postgresql_version: 13
postgresql_apt_dependencies: ["python3-psycopg2", "locales"]

postgresql_port: 5432
postgresql_listen_addresses:
  - "*"
postgresql_pg_hba_default:
  - { type: local, database: all, user: postgres, address: "", method: trust }
  - { type: local, database: all, user: all, address: "", method: md5 }
  - { type: host, database: all, user: all, address: "::1/128", method: md5 }
  - { type: host, database: all, user: all, address: "0.0.0.0/0", method: md5 }

postgresql_max_connections: 1000
